version: '3'
services:
  redis:
    image: redis
    volumes:
      - db-data:/data
  web:
    depends_on:
      - redis
    build: .
    container_name: project-devops
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  db-data: