version: '3'
services:
  redis:
    image: redis
    volumes:
      - db-data:/data
  web:
    # COMPLETE HERE
    build: .
    container_name: project-devops
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  db-data: